package diag

var (
	ErrPreparsingFailed = templateErr(CategoryInternal, "Preparsing did not return a valid HIR file")
	ErrVisitorPanic     = templateErr(CategoryInternal, "internal error while building HIR for %s: %s (this usually means the source has a syntax error that confuses the visitor — fix the syntax errors reported above first)")
	ErrPassPanic        = templateErr(CategoryInternal, "internal error during compiler pass '%s': %s (this usually means a syntax or binding error earlier in the file produced an inconsistent HIR — fix the diagnostics above first)")

	ErrUnexpectedEOF   = templateErr(CategorySyntax, "Unexpected end of file")
	ErrUnexpectedToken = templateErr(CategorySyntax, "Unexpected token: %s")
	ErrInvalidOperator = templateErr(CategorySyntax, "Invalid operator: %s")
	ErrInvalidLiteral  = templateErr(CategorySyntax, "Invalid literal: %s, expected %s")

	ErrRedeclaration                  = templateErr(CategorySemantic, "Could not declare symbol %s in scope %d: already declared!")
	ErrUndeclaredSymbol               = templateErr(CategorySemantic, "Undeclared symbol: %s")
	ErrTopLevelCycle                  = templateErr(CategorySemantic, "Cyclic top-level initialization detected: %s")
	ErrInvalidControlFlowDepth        = templateErr(CategorySemantic, "Invalid control flow depth for %s statement; it must be a non-negative (0 excluded) integer")
	ErrUnreachableCode                = templateErr(CategorySemantic, "Unreachable code detected")
	ErrMissingWhenDefault             = templateErr(CategorySemantic, "'when' statement is missing a default case")
	ErrSharedExternRequiresBothSides  = templateErr(CategorySemantic, "extern '%s' in a shared file must use a shared mapping with both 'frontend' and 'backend' branches")
	ErrInterfaceNotImplemented        = templateErr(CategorySemantic, "type '%s' declares 'implements %s' but does not provide method '%s'")
	ErrInterfaceMethodSigMismatch     = templateErr(CategorySemantic, "type '%s' method '%s' does not match the signature required by interface '%s'")
	ErrMixinNotFound                  = templateErr(CategorySemantic, "mixin '%s' is not declared")
	ErrMixinFieldTypeConflict         = templateErr(CategorySemantic, "field '%s' in type '%s' conflicts with mixin '%s': types differ")
	ErrAsyncInSyncContext             = templateErr(CategorySemantic, "async function call cannot be lifted in this context: %s")
	ErrWireOnShared                   = templateErr(CategorySemantic, "wired function '%s' cannot be hosted on `on shared` (wires are direction-specific: backend wire funcs are called from the frontend, frontend wire funcs are called from the backend over a session)")
	ErrWireNonTransferableType        = templateErr(CategorySemantic, "wired '%s' has a non-transferable type (interfaces, unconstrained generics, or function types cannot cross the wire boundary)")
	ErrWireRouteConflict              = templateErr(CategorySemantic, "wired route %s %s collides with previously declared function '%s'")
	ErrSessionOutsideWired            = templateErr(CategorySemantic, "@-session can only be used inside the body of a wired function on the backend side")
	ErrSessionOnFrontend              = templateErr(CategorySemantic, "@-session is backend-only; the frontend has no access to wire sessions")
	ErrWireVarNeedsType               = templateErr(CategorySemantic, "wired var/const '%s' needs an explicit type annotation (the type is used to build the JSON contract)")
	ErrUnknownWireRuleset             = templateErr(CategorySemantic, "unknown wire ruleset '%s'")
	ErrReactiveOnConst                = templateErr(CategorySemantic, "`@reactive` cannot be applied to `const` declaration '%s' (reactive requires mutability; use `let` instead)")
	ErrFrontendWireOffSession         = templateErr(CategorySemantic, "frontend wire '%[1]s' must be called through a session handle: `@.%[1]s(...)`, `someSession.%[1]s(...)`, or `sessions.broadcast().%[1]s(...)`")
	ErrWireInvalidTransport           = templateErr(CategorySemantic, "wire(transport: %q) on '%s' is not supported; expected one of: \"http\", \"ws\", \"sse\", \"raw\"")
	ErrWireTransportSideMismatch      = templateErr(CategorySemantic, "wire(transport: %q) on '%s' is invalid for a %s wire (backend wires can only use http, ws, or raw; frontend wires can only use ws or sse)")
	ErrWireRawBadSignature            = templateErr(CategorySemantic, "wire(transport: \"raw\") '%s' must take exactly two `any` parameters (`req`, `res`); got %d parameters")
	ErrWireRawBadParamType            = templateErr(CategorySemantic, "wire(transport: \"raw\") '%s' parameters must be typed `http.Request` and `http.Response` (in that order) — import \"std/http\" and use the typed handles so the compiler can catch swapped arguments at compile time")
	ErrWireRawBadReturn               = templateErr(CategorySemantic, "wire(transport: \"raw\") '%s' must not return a value — write to the response via `std/http` helpers on the `res` handle instead")
	ErrWireConflictingParamBinding    = templateErr(CategorySemantic, "wired param '%s' has conflicting bindings (already bound as %s, also annotated as %s); pick one of @query/@path/@header/@cookie/@body")
	ErrWirePathParamMissing           = templateErr(CategorySemantic, "wired param '%s' is annotated `@path` but `%s` has no `:%[1]s` placeholder; add it to the path or pick a different binding")
	ErrAnnotationNotConst             = templateErr(CategorySemantic, "annotation '@%s' argument must be a compile-time constant (literal or const-named string/int/bool, or a `+` of those)")
	ErrExternTypeInSharedFile         = templateErr(CategorySemantic, "extern type/interface '%s' is not allowed in a shared file; native bindings are side-specific. Put them in a backend or frontend file instead.")
	ErrExternTypeWrongSide            = templateErr(CategorySemantic, "extern type '%s' is %s-only and cannot be referenced from a %s file")
	ErrExternModuleVersionConflict    = templateErr(CategorySemantic, "extern Go module '%s' is pinned to conflicting versions: '%s' (here) vs. '%s' (declared elsewhere); reconcile the `@version` selectors so every extern block for this module agrees")
	ErrExternModuleVersionInvalid     = templateErr(CategorySemantic, "extern Go module '%s' has an invalid version pin '%s': expected a Go module version such as 'v1.2.3', 'v1.2.3-pre', or 'latest'")
	ErrImportSideMismatch             = templateErr(CategorySemantic, "cannot import %s package '%s' from a %s file: %s files may only import %s packages")
	ErrCastNotAllowed                 = templateErr(CategorySemantic, "cannot cast %s to %s: explicit `as` is only supported between compatible concrete types or when one side is `any`")
	ErrCastFromOption                 = templateErr(CategorySemantic, "cannot cast option<%s> directly to %s: unwrap the option first with `value!` (force-unwrap) or `value ?? fallback` (default), then cast")
	ErrImplicitAnyNarrowing           = templateErr(CategorySemantic, "implicit conversion from `any` to %s is not allowed; use an explicit cast (`value as %s` or `value as? %s`)")
	ErrPrivateFieldAccess             = templateErr(CategorySemantic, "field '%s' on type '%s' is private and may only be accessed from the type's own methods (via `this.%s`)")
	ErrPrivateSymbolAccess            = templateErr(CategorySemantic, "'%s' is package-private (names starting with a single `_` are not visible outside their declaring package); declared in '%s'")
	ErrTagAnnotationMalformed         = templateErr(CategorySemantic, "`@structTag` must have exactly two string arguments (`@structTag(\"<key>\", \"<value>\")`): %s")
	ErrSharedFieldNonTransferable     = templateErr(CategorySemantic, "shared field '%s' has a non-transferable type %s (shared members must use primitives, options, lists/maps/tuples of transferable, or other shared types)")
	ErrSharedReferencesBackendField   = templateErr(CategorySemantic, "shared method body of '%s.%s' may not reference non-shared field '%s' (only fields marked `shared` on the same type are visible)")
	ErrSharedReferencesBackendMethod  = templateErr(CategorySemantic, "shared method body of '%s.%s' may not call non-shared method '%s' on this type")
	ErrSharedReferencesBackendSymbol  = templateErr(CategorySemantic, "shared method body of '%s.%s' may not reference '%s' (allowed: `this`, parameters, local declarations, and symbols from `on shared` packages)")
	ErrSharedReferencesBackendPackage = templateErr(CategorySemantic, "shared method body of '%s.%s' may not call function '%s' from non-shared package '%s'")
	ErrSharedSignatureNonTransferable = templateErr(CategorySemantic, "shared member '%s.%s' has a non-transferable type %s in its signature (shared signatures must use primitives, options, lists/maps/tuples of transferable, or other shared types)")
	ErrInterfaceSharedMethodNotShared = templateErr(CategorySemantic, "type '%s' implements shared interface '%s' but its method '%s' is not marked `shared`; add the `shared` modifier so the method body emits on both sides")
	ErrSynthDuplicateName             = templateErr(CategorySemantic, "synth '%s' is already declared elsewhere in the build; synth names share a single global namespace, so two `synth %s` declarations cannot coexist")
	ErrSynthTargetMismatch            = templateErr(CategorySemantic, "synth '%s' applies to %s targets, but it is used on '%s' which is a different kind")
	ErrSynthArgCountMismatch          = templateErr(CategorySemantic, "synth '%s' expects %d argument(s), got %d")
	ErrSynthRecursionLimit            = templateErr(CategorySemantic, "synth '%s' expansion exceeded the recursion limit (%d); likely a cycle where a synth emits an annotation that recursively triggers itself")
	ErrSynthUnknownBind               = templateErr(CategorySemantic, "synth body references unknown bind '%s'; it must be either the synth's target bind or a for-loop iteration variable in scope")
	ErrSynthUnknownMember             = templateErr(CategorySemantic, "synth `for ... in %s.%s` references a member that does not exist on this kind of bind; known members are `fields`/`methods`/`ctors` (on type) and `params` (on func/method/ctor)")
	ErrSynthMemberOnNonType           = templateErr(CategorySemantic, "synth `emit %s` can only be used inside a synth declared `on type T` (current target bind '%s' is not a type)")
	ErrSynthSideMismatch              = templateErr(CategorySemantic, "synth '%s' is declared `on %s` and cannot be used in a file on side `%s` (the file's side must match, or be `shared` for backend/frontend-restricted synths)")
	ErrEmbedNotConst                  = templateErr(CategorySemantic, "`@embed` requires a `const` declaration (got `let`); the embedded contents are baked in at compile time and cannot be reassigned")
	ErrEmbedBadType                   = templateErr(CategorySemantic, "`@embed` on '%s' requires a declared type of `string` (for text) or `[]byte` / `bytes` (for binary); got %s")
	ErrEmbedBadPath                   = templateErr(CategorySemantic, "`@embed` path must be a relative path string literal (got %s); paths are resolved against the declaring file's directory")
	ErrEmbedFileNotFound              = templateErr(CategorySemantic, "`@embed` on '%s' cannot find file %s (resolved to %s)")
	ErrEmbedFileTooLarge              = templateErr(CategorySemantic, "`@embed` on '%s' refuses to embed %s (%d bytes); the size cap is %d bytes — raise it in sova.toml under `[build.embed] max-bytes` if you really need this")
	ErrEmbedPathEscapesProject        = templateErr(CategorySemantic, "`@embed` path %s escapes the project root after resolution; embeds must reference files inside the project tree (including dependency packages)")
	ErrEmbedSassUnavailable           = templateErr(CategorySemantic, "`@embed` on '%s' (%s) targets a .scss/.sass file but no Sass preprocessor is available; install `sass` (https://sass-lang.com/install) and ensure it's on PATH, or pin its location via `[build.scss] command = \"<path>\"` in sova.toml")
	ErrEmbedSassFailed                = templateErr(CategorySemantic, "`@embed` on '%s' (%s) failed Sass preprocessing: %s")

	ErrTypeMismatch        = templateErr(CategoryType, "Type mismatch: expected %s, got %s")
	ErrTypeNotIndexable    = templateErr(CategoryType, "Type %s is not indexable")
	ErrUnknownType         = templateErr(CategoryType, "Unknown %s type")
	ErrFuncParamMismatch   = templateErr(CategoryType, "Function parameter type mismatch; found func %s but failed on: %s")
	ErrTypeInferenceFailed = templateErr(CategoryType, "Type inference failed; could not infer type for %s")

	ErrOptionReturnMismatch     = templateErr(CategoryType, "Cannot infer option return type: non-none returns have incompatible types")
	ErrInvalidGuardOptionUnwrap = templateErr(CategoryType, "Cannot unwrap non-variable option in guard statement")
)
