package diag

var (
	ErrPreparsingFailed = templateErr(CategoryInternal, "Preparsing did not return a valid HIR file")

	ErrUnexpectedEOF   = templateErr(CategorySyntax, "Unexpected end of file")
	ErrUnexpectedToken = templateErr(CategorySyntax, "Unexpected token: %s")
	ErrInvalidOperator = templateErr(CategorySyntax, "Invalid operator: %s")
	ErrInvalidLiteral  = templateErr(CategorySyntax, "Invalid literal: %s, expected %s")

	ErrRedeclaration                  = templateErr(CategorySemantic, "Could not declare symbol %s in scope %d: already declared!")
	ErrUndeclaredSymbol               = templateErr(CategorySemantic, "Undeclared symbol: %s")
	ErrTopLevelCycle                  = templateErr(CategorySemantic, "Cyclic top-level initialization detected: %s")
	ErrInvalidControlFlowDepth        = templateErr(CategorySemantic, "Invalid control flow depth for %s statement; it must be a non-negative (0 excluded) integer")
	ErrUnreachableCode                = templateErr(CategorySemantic, "Unreachable code detected")
	ErrMissingWhenDefault             = templateErr(CategorySemantic, "'when' statement is missing a default case")
	ErrSharedExternRequiresBothSides  = templateErr(CategorySemantic, "extern '%s' in a shared file must use a shared mapping with both 'frontend' and 'backend' branches")
	ErrInterfaceNotImplemented        = templateErr(CategorySemantic, "type '%s' declares 'implements %s' but does not provide method '%s'")
	ErrInterfaceMethodSigMismatch     = templateErr(CategorySemantic, "type '%s' method '%s' does not match the signature required by interface '%s'")
	ErrMixinNotFound                  = templateErr(CategorySemantic, "mixin '%s' is not declared")
	ErrMixinFieldTypeConflict         = templateErr(CategorySemantic, "field '%s' in type '%s' conflicts with mixin '%s': types differ")
	ErrAsyncInSyncContext             = templateErr(CategorySemantic, "async function call cannot be lifted in this context: %s")
	ErrWireOnShared                   = templateErr(CategorySemantic, "wired function '%s' cannot be hosted on `on shared` (wires are direction-specific: backend wire funcs are called from the frontend, frontend wire funcs are called from the backend over a session)")
	ErrWireNonTransferableType        = templateErr(CategorySemantic, "wired '%s' has a non-transferable type (interfaces, unconstrained generics, or function types cannot cross the wire boundary)")
	ErrWireRouteConflict              = templateErr(CategorySemantic, "wired route %s %s collides with previously declared function '%s'")
	ErrSessionOutsideWired            = templateErr(CategorySemantic, "@-session can only be used inside the body of a wired function on the backend side")
	ErrSessionOnFrontend              = templateErr(CategorySemantic, "@-session is backend-only; the frontend has no access to wire sessions")
	ErrWireVarNeedsType               = templateErr(CategorySemantic, "wired var/const '%s' needs an explicit type annotation (the type is used to build the JSON contract)")
	ErrUnknownWireRuleset             = templateErr(CategorySemantic, "unknown wire ruleset '%s'")
	ErrReactiveOnConst                = templateErr(CategorySemantic, "`@reactive` cannot be applied to `const` declaration '%s' (reactive requires mutability; use `let` instead)")
	ErrFrontendWireOffSession         = templateErr(CategorySemantic, "frontend wire '%[1]s' must be called through a session handle: `@.%[1]s(...)`, `someSession.%[1]s(...)`, or `sessions.broadcast().%[1]s(...)`")
	ErrWireInvalidTransport           = templateErr(CategorySemantic, "wire(transport: %q) on '%s' is not supported; expected one of: \"http\", \"ws\", \"sse\"")
	ErrWireTransportSideMismatch      = templateErr(CategorySemantic, "wire(transport: %q) on '%s' is invalid for a %s wire (backend wires can only use http or ws; frontend wires can only use ws or sse)")
	ErrAnnotationNotConst             = templateErr(CategorySemantic, "annotation '@%s' argument must be a compile-time constant (literal or const-named string/int/bool, or a `+` of those)")
	ErrExternTypeInSharedFile         = templateErr(CategorySemantic, "extern type/interface '%s' is not allowed in a shared file; native bindings are side-specific. Put them in a backend or frontend file instead.")
	ErrExternTypeWrongSide            = templateErr(CategorySemantic, "extern type '%s' is %s-only and cannot be referenced from a %s file")
	ErrExternModuleVersionConflict    = templateErr(CategorySemantic, "extern Go module '%s' is pinned to conflicting versions: '%s' (here) vs. '%s' (declared elsewhere); reconcile the `@version` selectors so every extern block for this module agrees")
	ErrExternModuleVersionInvalid     = templateErr(CategorySemantic, "extern Go module '%s' has an invalid version pin '%s': expected a Go module version such as 'v1.2.3', 'v1.2.3-pre', or 'latest'")
	ErrImportSideMismatch             = templateErr(CategorySemantic, "cannot import %s package '%s' from a %s file: %s files may only import %s packages")
	ErrCastNotAllowed                 = templateErr(CategorySemantic, "cannot cast %s to %s: explicit `as` is only supported between compatible concrete types or when one side is `any`")
	ErrImplicitAnyNarrowing           = templateErr(CategorySemantic, "implicit conversion from `any` to %s is not allowed; use an explicit cast (`value as %s` or `value as? %s`)")
	ErrPrivateFieldAccess             = templateErr(CategorySemantic, "field '%s' on type '%s' is private and may only be accessed from the type's own methods (via `this.%s`)")
	ErrPrivateSymbolAccess            = templateErr(CategorySemantic, "'%s' is package-private (names starting with a single `_` are not visible outside their declaring package); declared in '%s'")

	ErrTypeMismatch        = templateErr(CategoryType, "Type mismatch: expected %s, got %s")
	ErrTypeNotIndexable    = templateErr(CategoryType, "Type %s is not indexable")
	ErrUnknownType         = templateErr(CategoryType, "Unknown %s type")
	ErrFuncParamMismatch   = templateErr(CategoryType, "Function parameter type mismatch; found func %s but failed on: %s")
	ErrTypeInferenceFailed = templateErr(CategoryType, "Type inference failed; could not infer type for %s")

	ErrOptionReturnMismatch     = templateErr(CategoryType, "Cannot infer option return type: non-none returns have incompatible types")
	ErrInvalidGuardOptionUnwrap = templateErr(CategoryType, "Cannot unwrap non-variable option in guard statement")
)
