package pkgmgr

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

const LockfileFilename = "sova.lock"

const LockfileVersion = 1

type Lockfile struct {
	Version  int             `toml:"version"`
	Packages []LockedPackage `toml:"package"`
}

type LockedPackage struct {
	Name         string   `toml:"name"`
	Version      string   `toml:"version"`
	Source       string   `toml:"source"`
	Commit       string   `toml:"commit,omitempty"`
	Subdir       string   `toml:"subdir,omitempty"`
	Checksum     string   `toml:"checksum,omitempty"`
	Dependencies []string `toml:"dependencies,omitempty"`
}

func LoadLockfile(path string) (*Lockfile, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, false, nil
		}

		return nil, false, err
	}

	var lf Lockfile
	if err := toml.Unmarshal(data, &lf); err != nil {
		return nil, false, fmt.Errorf("parse %s: %w", path, err)
	}

	if lf.Version == 0 {
		lf.Version = LockfileVersion
	}

	if lf.Version != LockfileVersion {
		return nil, false, fmt.Errorf("lockfile %s: unsupported version %d (expected %d)", path, lf.Version, LockfileVersion)
	}

	sort.Slice(lf.Packages, func(i, j int) bool {
		if lf.Packages[i].Name == lf.Packages[j].Name {
			return lf.Packages[i].Version < lf.Packages[j].Version
		}

		return lf.Packages[i].Name < lf.Packages[j].Name
	})
	return &lf, true, nil
}

func (lf *Lockfile) Save(path string) error {
	if lf.Version == 0 {
		lf.Version = LockfileVersion
	}

	pkgs := make([]LockedPackage, len(lf.Packages))
	copy(pkgs, lf.Packages)
	sort.Slice(pkgs, func(i, j int) bool {
		if pkgs[i].Name == pkgs[j].Name {
			return pkgs[i].Version < pkgs[j].Version
		}

		return pkgs[i].Name < pkgs[j].Name
	})

	var b strings.Builder
	b.WriteString("# Auto-generated by sova. Do not edit by hand.\n")
	b.WriteString("# To update, run `sova update` or `sova update <pkg>`.\n\n")
	fmt.Fprintf(&b, "version = %d\n", lf.Version)
	for _, p := range pkgs {
		b.WriteString("\n[[package]]\n")
		fmt.Fprintf(&b, "name = %s\n", tomlQuote(p.Name))
		fmt.Fprintf(&b, "version = %s\n", tomlQuote(p.Version))
		fmt.Fprintf(&b, "source = %s\n", tomlQuote(p.Source))
		if p.Commit != "" {
			fmt.Fprintf(&b, "commit = %s\n", tomlQuote(p.Commit))
		}

		if p.Subdir != "" {
			fmt.Fprintf(&b, "subdir = %s\n", tomlQuote(p.Subdir))
		}

		if p.Checksum != "" {
			fmt.Fprintf(&b, "checksum = %s\n", tomlQuote(p.Checksum))
		}

		if len(p.Dependencies) > 0 {
			deps := make([]string, len(p.Dependencies))
			copy(deps, p.Dependencies)
			sort.Strings(deps)
			b.WriteString("dependencies = [\n")
			for _, d := range deps {
				fmt.Fprintf(&b, "    %s,\n", tomlQuote(d))
			}

			b.WriteString("]\n")
		}
	}

	tmp := path + ".tmp"
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}

	return os.Rename(tmp, path)
}

func (lf *Lockfile) FindByName(name string) (*LockedPackage, bool) {
	for i := range lf.Packages {
		if lf.Packages[i].Name == name {
			return &lf.Packages[i], true
		}
	}

	return nil, false
}

func tomlQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, `\u%04x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}

	b.WriteByte('"')
	return b.String()
}

func ComputeChecksum(rootDir string) (string, error) {
	type entry struct {
		rel  string
		hash string
	}

	var entries []entry
	err := filepath.WalkDir(rootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		rel, _ := filepath.Rel(rootDir, path)
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}

		first := strings.SplitN(rel, "/", 2)[0]
		if first == ".git" || first == ".sova" {
			if d.IsDir() {
				return filepath.SkipDir
			}

			return nil
		}

		if d.IsDir() {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}

		h := sha256.New()
		_, copyErr := io.Copy(h, f)
		f.Close()
		if copyErr != nil {
			return copyErr
		}

		entries = append(entries, entry{rel: rel, hash: hex.EncodeToString(h.Sum(nil))})
		return nil
	})
	if err != nil {
		return "", err
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].rel < entries[j].rel })
	overall := sha256.New()
	for _, e := range entries {
		overall.Write([]byte(e.rel))
		overall.Write([]byte{0})
		overall.Write([]byte(e.hash))
		overall.Write([]byte{0})
	}

	return "sha256:" + hex.EncodeToString(overall.Sum(nil)), nil
}
